// Centralized error codes
export const ErrorCodes = {
  // Shop errors
  SHOP_NOT_FOUND: 'SHOP_NOT_FOUND',
  SHOP_ALREADY_EXISTS: 'SHOP_ALREADY_EXISTS',

  // Product errors
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  INVALID_PRODUCT_DATA: 'INVALID_PRODUCT_DATA',

  // Auth errors
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_TOKEN: 'INVALID_TOKEN',

  // Shopify errors
  SHOPIFY_API_ERROR: 'SHOPIFY_API_ERROR',
  OAUTH_FAILED: 'OAUTH_FAILED',

  // System errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const
