import { useState, useEffect } from "react";
import type { LoaderFunctionArgs, HeadersFunction } from "react-router";
import { Link, useParams, useLoaderData, useNavigate } from "react-router";
import { authenticate } from "../shopify.server";
import { boundary } from "@shopify/shopify-app-react-router/server";
import { useAppBridge } from "@shopify/app-bridge-react";
import { ROUTES } from "../constants/routes";

// Types
interface Product {
  id: string;
  title: string;
  price: string;
  image: string;
}

interface LoaderData {
  product: Product | null;
  allProducts: Product[];
}

export const loader = async ({ request, params }: LoaderFunctionArgs) => {
  const { admin } = await authenticate.admin(request);
  const { id } = params;

  // Decode the product ID (it comes URL encoded)
  const productId = decodeURIComponent(id || "");

  // Fetch the specific product
  const productResponse = await admin.graphql(
    `#graphql
      query getProduct($id: ID!) {
        product(id: $id) {
          id
          title
          featuredImage {
            url
          }
          variants(first: 1) {
            edges {
              node {
                price
              }
            }
          }
        }
      }
    `,
    { variables: { id: productId } }
  );

  const productData = await productResponse.json();
  
  // Fetch all products for search/browse
  const allProductsResponse = await admin.graphql(
    `#graphql
      query getAllProducts {
        products(first: 50) {
          edges {
            node {
              id
              title
              featuredImage {
                url
              }
              variants(first: 1) {
                edges {
                  node {
                    price
                  }
                }
              }
            }
          }
        }
      }
    `
  );

  const allProductsData = await allProductsResponse.json();

  const product = productData.data.product ? {
    id: productData.data.product.id,
    title: productData.data.product.title,
    price: productData.data.product.variants.edges[0]?.node.price || "0.00",
    image: productData.data.product.featuredImage?.url || ""
  } : null;

  const allProducts: Product[] = allProductsData.data.products.edges
    .map((edge: any) => ({
      id: edge.node.id,
      title: edge.node.title,
      price: edge.node.variants.edges[0]?.node.price || "0.00",
      image: edge.node.featuredImage?.url || ""
    }))
    .filter((p: Product) => p.id !== productId); // Exclude current product

  return { product, allProducts };
};

export default function EditProductRecommendationsPage() {
  const { product, allProducts } = useLoaderData<LoaderData>();
  const navigate = useNavigate();
  const shopify = useAppBridge();
  
  const [complementaryProducts, setComplementaryProducts] = useState<Product[]>([]);
  const [relatedProducts, setRelatedProducts] = useState<Product[]>([]);
  const [complementarySearch, setComplementarySearch] = useState("");
  const [relatedSearch, setRelatedSearch] = useState("");
  const [hideAutoGenerated, setHideAutoGenerated] = useState(false);
  const [showComplementaryBrowse, setShowComplementaryBrowse] = useState(false);
  const [showRelatedBrowse, setShowRelatedBrowse] = useState(false);

  // Load saved recommendations from sessionStorage
  useEffect(() => {
    if (product) {
      const saved = sessionStorage.getItem(`recommendations_${product.id}`);
      if (saved) {
        const data = JSON.parse(saved);
        setComplementaryProducts(data.complementary || []);
        setRelatedProducts(data.related || []);
        setHideAutoGenerated(data.hideAutoGenerated || false);
      }
    }
  }, [product]);

  // Filter products based on search
  const filteredComplementary = allProducts.filter(p => 
    p.title.toLowerCase().includes(complementarySearch.toLowerCase()) &&
    !complementaryProducts.find(cp => cp.id === p.id)
  );

  const filteredRelated = allProducts.filter(p => 
    p.title.toLowerCase().includes(relatedSearch.toLowerCase()) &&
    !relatedProducts.find(rp => rp.id === p.id)
  );

  // Add product to complementary
  const addComplementary = (p: Product) => {
    setComplementaryProducts([...complementaryProducts, p]);
    setComplementarySearch("");
    setShowComplementaryBrowse(false);
  };

  // Add product to related
  const addRelated = (p: Product) => {
    setRelatedProducts([...relatedProducts, p]);
    setRelatedSearch("");
    setShowRelatedBrowse(false);
  };

  // Remove product from complementary
  const removeComplementary = (id: string) => {
    setComplementaryProducts(complementaryProducts.filter(p => p.id !== id));
  };

  // Remove product from related
  const removeRelated = (id: string) => {
    setRelatedProducts(relatedProducts.filter(p => p.id !== id));
  };

  // Handle save
  const handleSave = () => {
    if (product) {
      const data = {
        complementary: complementaryProducts,
        related: relatedProducts,
        hideAutoGenerated
      };
      sessionStorage.setItem(`recommendations_${product.id}`, JSON.stringify(data));
      shopify.toast.show("Recommendations saved successfully!");
      navigate(ROUTES.RECOMMENDATIONS);
    }
  };

  if (!product) {
    return (
      <s-page>
        <s-box padding="large">
          <s-text>Product not found</s-text>
        </s-box>
      </s-page>
    );
  }

  return (
    <s-page>
      {/* Header */}
      <s-box paddingBlockEnd="base">
        <s-grid gridTemplateColumns="1fr auto" gap="base" alignItems="center">
          <Link 
            to={ROUTES.RECOMMENDATIONS}
            style={{ display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer', textDecoration: 'none' }}
          >
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" width="20" height="20" fill="#5c5f62">
              <path d="M17 9h-11.586l5.293-5.293a1 1 0 0 0-1.414-1.414l-7 7a1 1 0 0 0 0 1.414l7 7a1 1 0 0 0 1.414-1.414l-5.293-5.293h11.586a1 1 0 1 0 0-2Z"/>
            </svg>
            <span style={{ fontSize: '20px', fontWeight: 'bold', color: 'black' }}>
              Edit product recommendations
            </span>
          </Link>
          <button
            style={{
              padding: '8px 16px',
              border: '1px solid #c9cccf',
              borderRadius: '8px',
              backgroundColor: 'white',
              cursor: 'pointer',
              fontSize: '14px'
            }}
          >
            View
          </button>
        </s-grid>
      </s-box>

      {/* Product Info Section */}
      <s-section>
        <s-box background="base" borderRadius="base" border="base" padding="large">
          <s-text color="subdued">
            <strong>Product</strong>
          </s-text>
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px', marginTop: '12px' }}>
            {/* Product Image */}
            <div
              style={{
                width: '80px',
                height: '80px',
                borderRadius: '8px',
                backgroundColor: '#f6f6f7',
                border: '1px solid #e1e3e5',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                overflow: 'hidden'
              }}
            >
              {product.image ? (
                <img 
                  src={product.image} 
                  alt={product.title}
                  style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                />
              ) : (
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" width="32" height="32" fill="#8c9196">
                  <path d="M2.5 4A1.5 1.5 0 0 1 4 2.5h12A1.5 1.5 0 0 1 17.5 4v12a1.5 1.5 0 0 1-1.5 1.5H4A1.5 1.5 0 0 1 2.5 16V4Z"/>
                </svg>
              )}
            </div>
            {/* Product Info */}
            <div>
              <a href="#" style={{ color: '#2c6ecb', textDecoration: 'none', fontWeight: '500' }}>
                {product.title}
              </a>
              <div style={{ color: '#6d7175', marginTop: '4px' }}>
                ₹{product.price}
              </div>
            </div>
          </div>
        </s-box>
      </s-section>

      {/* Edit Complementary Products Section */}
      <s-section>
        <s-box background="base" borderRadius="base" border="base" padding="large">
          <s-text>
            <strong>Edit complementary products</strong>
          </s-text>
          <s-box paddingBlockStart="small">
            <s-text color="subdued">
              Select products that could be bought in addition to{" "}
              <a href="#" style={{ color: '#2c6ecb', textDecoration: 'none' }}>{product.title}</a>.
            </s-text>
          </s-box>

          {/* Search Input */}
          <s-box paddingBlockStart="base">
            <div style={{ display: 'flex', gap: '8px' }}>
              <div style={{ flex: 1, position: 'relative' }}>
                <div style={{ 
                  display: 'flex', 
                  alignItems: 'center', 
                  gap: '8px',
                  padding: '10px 12px',
                  border: '1px solid #c9cccf',
                  borderRadius: '8px',
                  backgroundColor: 'white'
                }}>
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" width="16" height="16" fill="#8c9196">
                    <path d="M8 12a4 4 0 1 1 0-8 4 4 0 0 1 0 8Zm9.707 4.293-4.82-4.82a5.968 5.968 0 0 0 1.113-3.473 6 6 0 1 0-6 6 5.968 5.968 0 0 0 3.473-1.113l4.82 4.82a.997.997 0 0 0 1.414 0 .999.999 0 0 0 0-1.414Z"/>
                  </svg>
                  <input
                    type="text"
                    placeholder="Search products"
                    value={complementarySearch}
                    onChange={(e) => setComplementarySearch(e.target.value)}
                    style={{
                      border: 'none',
                      outline: 'none',
                      fontSize: '14px',
                      flex: 1,
                      backgroundColor: 'transparent'
                    }}
                  />
                </div>
                {/* Search Results Dropdown */}
                {complementarySearch && filteredComplementary.length > 0 && (
                  <div style={{
                    position: 'absolute',
                    top: '100%',
                    left: 0,
                    right: 0,
                    backgroundColor: 'white',
                    border: '1px solid #c9cccf',
                    borderRadius: '8px',
                    marginTop: '4px',
                    maxHeight: '200px',
                    overflowY: 'auto',
                    zIndex: 10
                  }}>
                    {filteredComplementary.slice(0, 5).map(p => (
                      <div
                        key={p.id}
                        onClick={() => addComplementary(p)}
                        style={{
                          padding: '8px 12px',
                          cursor: 'pointer',
                          display: 'flex',
                          alignItems: 'center',
                          gap: '8px'
                        }}
                        onMouseEnter={(e) => e.currentTarget.style.backgroundColor = '#f6f6f7'}
                        onMouseLeave={(e) => e.currentTarget.style.backgroundColor = 'white'}
                      >
                        <div style={{ width: '32px', height: '32px', borderRadius: '4px', backgroundColor: '#f6f6f7', overflow: 'hidden' }}>
                          {p.image && <img src={p.image} alt={p.title} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />}
                        </div>
                        <span>{p.title}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
              <button
                onClick={() => setShowComplementaryBrowse(!showComplementaryBrowse)}
                style={{
                  padding: '10px 16px',
                  border: '1px solid #c9cccf',
                  borderRadius: '8px',
                  backgroundColor: 'white',
                  cursor: 'pointer',
                  fontSize: '14px'
                }}
              >
                Browse
              </button>
            </div>
          </s-box>

          {/* Selected Complementary Products */}
          {complementaryProducts.length > 0 ? (
            <s-box paddingBlockStart="base">
              {complementaryProducts.map(p => (
                <div key={p.id} style={{ 
                  display: 'flex', 
                  alignItems: 'center', 
                  justifyContent: 'space-between',
                  padding: '8px',
                  borderBottom: '1px solid #e1e3e5'
                }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <div style={{ width: '32px', height: '32px', borderRadius: '4px', backgroundColor: '#f6f6f7', overflow: 'hidden' }}>
                      {p.image && <img src={p.image} alt={p.title} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />}
                    </div>
                    <span>{p.title}</span>
                  </div>
                  <button
                    onClick={() => removeComplementary(p.id)}
                    style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#bf0711' }}
                  >
                    ✕
                  </button>
                </div>
              ))}
            </s-box>
          ) : (
            /* Empty State */
            <s-box paddingBlockStart="large" paddingBlockEnd="large">
              <div style={{ textAlign: 'center' }}>
                <svg width="120" height="80" viewBox="0 0 120 80" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <rect x="10" y="10" width="45" height="60" rx="4" fill="#f6f6f7" stroke="#e1e3e5"/>
                  <rect x="65" y="10" width="45" height="35" rx="4" fill="#f6f6f7" stroke="#e1e3e5"/>
                  <rect x="70" y="15" width="15" height="15" rx="2" fill="#e1e3e5"/>
                  <rect x="90" y="15" width="15" height="4" rx="2" fill="#e1e3e5"/>
                  <rect x="90" y="22" width="10" height="4" rx="2" fill="#e1e3e5"/>
                  <rect x="70" y="35" width="35" height="4" rx="2" fill="#ffc96b"/>
                </svg>
                <s-box paddingBlockStart="small">
                  <s-text color="subdued">
                    No complementary products yet. Search to add products.
                  </s-text>
                </s-box>
              </div>
            </s-box>
          )}

          {/* Browse Modal for Complementary */}
          {showComplementaryBrowse && (
            <s-box paddingBlockStart="base">
              <div style={{
                border: '1px solid #c9cccf',
                borderRadius: '8px',
                backgroundColor: 'white',
                maxHeight: '300px',
                overflowY: 'auto'
              }}>
                <div style={{ padding: '12px', borderBottom: '1px solid #e1e3e5', fontWeight: '500' }}>
                  Select products ({filteredComplementary.length} available)
                </div>
                {filteredComplementary.map(p => (
                  <div
                    key={p.id}
                    onClick={() => addComplementary(p)}
                    style={{
                      padding: '12px',
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '12px',
                      borderBottom: '1px solid #f1f1f1'
                    }}
                    onMouseEnter={(e) => e.currentTarget.style.backgroundColor = '#f6f6f7'}
                    onMouseLeave={(e) => e.currentTarget.style.backgroundColor = 'white'}
                  >
                    <div style={{ 
                      width: '40px', 
                      height: '40px', 
                      borderRadius: '4px', 
                      backgroundColor: '#f6f6f7', 
                      border: '1px solid #e1e3e5',
                      overflow: 'hidden',
                      flexShrink: 0
                    }}>
                      {p.image ? (
                        <img src={p.image} alt={p.title} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                      ) : (
                        <div style={{ width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" width="20" height="20" fill="#8c9196">
                            <path d="M2.5 4A1.5 1.5 0 0 1 4 2.5h12A1.5 1.5 0 0 1 17.5 4v12a1.5 1.5 0 0 1-1.5 1.5H4A1.5 1.5 0 0 1 2.5 16V4Z"/>
                          </svg>
                        </div>
                      )}
                    </div>
                    <div>
                      <div style={{ fontWeight: '500' }}>{p.title}</div>
                      <div style={{ color: '#6d7175', fontSize: '13px' }}>₹{p.price}</div>
                    </div>
                  </div>
                ))}
                {filteredComplementary.length === 0 && (
                  <div style={{ padding: '20px', textAlign: 'center', color: '#6d7175' }}>
                    No more products available
                  </div>
                )}
              </div>
            </s-box>
          )}

          {/* Learn More Link */}
          <s-box paddingBlockStart="base">
            <s-text color="subdued">
              Not seeing complementary products on your store?{" "}
              <a href="https://help.shopify.com/en/manual/online-store/search-and-discovery/product-recommendations" target="_blank" rel="noopener noreferrer" style={{ color: '#2c6ecb', textDecoration: 'none' }}>
                Learn more
              </a>
            </s-text>
          </s-box>
        </s-box>
      </s-section>

      {/* Edit Related Products Section */}
      <s-section>
        <s-box background="base" borderRadius="base" border="base" padding="large">
          <s-text>
            <strong>Edit related products</strong>
          </s-text>
          <s-box paddingBlockStart="small">
            <s-text color="subdued">
              Select products that are good alternatives to{" "}
              <a href="#" style={{ color: '#2c6ecb', textDecoration: 'none' }}>{product.title}</a>.
            </s-text>
          </s-box>

          {/* Search Input */}
          <s-box paddingBlockStart="base">
            <div style={{ display: 'flex', gap: '8px' }}>
              <div style={{ flex: 1, position: 'relative' }}>
                <div style={{ 
                  display: 'flex', 
                  alignItems: 'center', 
                  gap: '8px',
                  padding: '10px 12px',
                  border: '1px solid #c9cccf',
                  borderRadius: '8px',
                  backgroundColor: 'white'
                }}>
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" width="16" height="16" fill="#8c9196">
                    <path d="M8 12a4 4 0 1 1 0-8 4 4 0 0 1 0 8Zm9.707 4.293-4.82-4.82a5.968 5.968 0 0 0 1.113-3.473 6 6 0 1 0-6 6 5.968 5.968 0 0 0 3.473-1.113l4.82 4.82a.997.997 0 0 0 1.414 0 .999.999 0 0 0 0-1.414Z"/>
                  </svg>
                  <input
                    type="text"
                    placeholder="Search products"
                    value={relatedSearch}
                    onChange={(e) => setRelatedSearch(e.target.value)}
                    style={{
                      border: 'none',
                      outline: 'none',
                      fontSize: '14px',
                      flex: 1,
                      backgroundColor: 'transparent'
                    }}
                  />
                </div>
                {/* Search Results Dropdown */}
                {relatedSearch && filteredRelated.length > 0 && (
                  <div style={{
                    position: 'absolute',
                    top: '100%',
                    left: 0,
                    right: 0,
                    backgroundColor: 'white',
                    border: '1px solid #c9cccf',
                    borderRadius: '8px',
                    marginTop: '4px',
                    maxHeight: '200px',
                    overflowY: 'auto',
                    zIndex: 10
                  }}>
                    {filteredRelated.slice(0, 5).map(p => (
                      <div
                        key={p.id}
                        onClick={() => addRelated(p)}
                        style={{
                          padding: '8px 12px',
                          cursor: 'pointer',
                          display: 'flex',
                          alignItems: 'center',
                          gap: '8px'
                        }}
                        onMouseEnter={(e) => e.currentTarget.style.backgroundColor = '#f6f6f7'}
                        onMouseLeave={(e) => e.currentTarget.style.backgroundColor = 'white'}
                      >
                        <div style={{ width: '32px', height: '32px', borderRadius: '4px', backgroundColor: '#f6f6f7', overflow: 'hidden' }}>
                          {p.image && <img src={p.image} alt={p.title} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />}
                        </div>
                        <span>{p.title}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
              <button
                onClick={() => setShowRelatedBrowse(!showRelatedBrowse)}
                style={{
                  padding: '10px 16px',
                  border: '1px solid #c9cccf',
                  borderRadius: '8px',
                  backgroundColor: 'white',
                  cursor: 'pointer',
                  fontSize: '14px'
                }}
              >
                Browse
              </button>
            </div>
          </s-box>

          {/* Selected Related Products */}
          {relatedProducts.length > 0 ? (
            <s-box paddingBlockStart="base">
              {relatedProducts.map(p => (
                <div key={p.id} style={{ 
                  display: 'flex', 
                  alignItems: 'center', 
                  justifyContent: 'space-between',
                  padding: '8px',
                  borderBottom: '1px solid #e1e3e5'
                }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <div style={{ width: '32px', height: '32px', borderRadius: '4px', backgroundColor: '#f6f6f7', overflow: 'hidden' }}>
                      {p.image && <img src={p.image} alt={p.title} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />}
                    </div>
                    <span>{p.title}</span>
                  </div>
                  <button
                    onClick={() => removeRelated(p.id)}
                    style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#bf0711' }}
                  >
                    ✕
                  </button>
                </div>
              ))}
            </s-box>
          ) : (
            /* Empty State */
            <s-box paddingBlockStart="large" paddingBlockEnd="large">
              <div style={{ textAlign: 'center' }}>
                <svg width="120" height="80" viewBox="0 0 120 80" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <rect x="10" y="25" width="30" height="30" rx="4" fill="#f6f6f7" stroke="#e1e3e5"/>
                  <rect x="45" y="25" width="30" height="30" rx="4" fill="#f6f6f7" stroke="#e1e3e5"/>
                  <rect x="80" y="25" width="30" height="30" rx="4" fill="#f6f6f7" stroke="#e1e3e5"/>
                  <rect x="15" y="30" width="10" height="10" rx="2" fill="#e1e3e5"/>
                  <rect x="50" y="30" width="10" height="10" rx="2" fill="#e1e3e5"/>
                  <rect x="85" y="30" width="10" height="10" rx="2" fill="#e1e3e5"/>
                </svg>
                <s-box paddingBlockStart="small">
                  <s-text color="subdued">
                    No related products added yet. Search to add products.
                  </s-text>
                </s-box>
              </div>
            </s-box>
          )}

          {/* Browse Modal for Related */}
          {showRelatedBrowse && (
            <s-box paddingBlockStart="base">
              <div style={{
                border: '1px solid #c9cccf',
                borderRadius: '8px',
                backgroundColor: 'white',
                maxHeight: '300px',
                overflowY: 'auto'
              }}>
                <div style={{ padding: '12px', borderBottom: '1px solid #e1e3e5', fontWeight: '500' }}>
                  Select products ({filteredRelated.length} available)
                </div>
                {filteredRelated.map(p => (
                  <div
                    key={p.id}
                    onClick={() => addRelated(p)}
                    style={{
                      padding: '12px',
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '12px',
                      borderBottom: '1px solid #f1f1f1'
                    }}
                    onMouseEnter={(e) => e.currentTarget.style.backgroundColor = '#f6f6f7'}
                    onMouseLeave={(e) => e.currentTarget.style.backgroundColor = 'white'}
                  >
                    <div style={{ 
                      width: '40px', 
                      height: '40px', 
                      borderRadius: '4px', 
                      backgroundColor: '#f6f6f7', 
                      border: '1px solid #e1e3e5',
                      overflow: 'hidden',
                      flexShrink: 0
                    }}>
                      {p.image ? (
                        <img src={p.image} alt={p.title} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                      ) : (
                        <div style={{ width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" width="20" height="20" fill="#8c9196">
                            <path d="M2.5 4A1.5 1.5 0 0 1 4 2.5h12A1.5 1.5 0 0 1 17.5 4v12a1.5 1.5 0 0 1-1.5 1.5H4A1.5 1.5 0 0 1 2.5 16V4Z"/>
                          </svg>
                        </div>
                      )}
                    </div>
                    <div>
                      <div style={{ fontWeight: '500' }}>{p.title}</div>
                      <div style={{ color: '#6d7175', fontSize: '13px' }}>₹{p.price}</div>
                    </div>
                  </div>
                ))}
                {filteredRelated.length === 0 && (
                  <div style={{ padding: '20px', textAlign: 'center', color: '#6d7175' }}>
                    No more products available
                  </div>
                )}
              </div>
            </s-box>
          )}

          {/* Hide Auto-Generated Checkbox */}
          <s-box paddingBlockStart="base">
            <label style={{ display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer' }}>
              <input
                type="checkbox"
                checked={hideAutoGenerated}
                onChange={(e) => setHideAutoGenerated(e.target.checked)}
                style={{ width: '16px', height: '16px' }}
              />
              <s-text>Hide auto-generated recommendations</s-text>
            </label>
          </s-box>
        </s-box>
      </s-section>

      {/* Save Button */}
      <s-box paddingBlockStart="base">
        <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
          <button
            onClick={handleSave}
            style={{
              backgroundColor: complementaryProducts.length > 0 || relatedProducts.length > 0 ? '#008060' : '#d1d5db',
              color: 'white',
              border: 'none',
              borderRadius: '8px',
              padding: '8px 16px',
              fontSize: '14px',
              fontWeight: '500',
              cursor: complementaryProducts.length > 0 || relatedProducts.length > 0 ? 'pointer' : 'not-allowed'
            }}
          >
            Save
          </button>
        </div>
      </s-box>
    </s-page>
  );
}

export const headers: HeadersFunction = (headersArgs) => {
  return boundary.headers(headersArgs);
};

